name: github_context

on:
  push:
    branches:
      - github_context

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Dump github environment
        run:   printenv
        shell: bash
